name: "publish npm"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Update to use Node.js 16
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm install

      - name: Publish to npm
        run: npm publish --access public --verbose  # Adding verbose flag for detailed logs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH }}
